### PR TITLE
Fix text nodes

### PR DESCRIPTION
**Pull request by DannyBen**
This is an initial PR that currently just adds a failing test to demonstrate the problem in #18.

To test run:

```shell
$ run spec svg_source
#or 
$ run spec :focus
```

### CODE REVIEW

**Comment by DannyBen** [comment]
@gingermusketeer right now the converter fails when there is either a CSS node or a text node. I have attempted to mess around with it, but got lost in the nokogiri maze. If you have time to take a look, my guess is that you can solve it faster than I can.

Feel free to push to this PR - I will try to avoid pushing to it any further - I just wanted to prepare an easy reproduction "red test".

**Comment by gingermusketeer** [comment]
@DannyBen How does that look?

**Comment by DannyBen** [comment]
Yeah, that far I think I reached.

There are a couple of problems with it at least:

1. Victor has special handling for CSS
2. Victor allows for writing text nodes like this: `text "hello world", x: 10, y: 10`

The SVG fixture under test was actually generated by this Ruby code:

```ruby
build do
  css['.main'] = {
    stroke: "green"
  }

  text "without attributes"
  
  text "with attributes", x: 10, y: 10
  
  text x: 10, y: 10 do
    _ "with"
    tspan "block", font_weight: 'bold'
    _ "and attributes"
  end

end
```

So I was hoping we would be able to convert SVG to this format.

Also - I was wondering, in the `Parser` class - why did you choose to return a 3-element array, as opposed to an object, or a hash? This made it a little harder for me to try and follow the code to a solution.

`["_", {}, cleaned_text]` is harder to interpret, then say:

```ruby
{
  type: :text,
  attributes: nil,
  body: cleaned_text
}
```

**Comment by DannyBen** [comment]
Here is an example updated parser, that converts nodes to a hash instead of array + recognizes (but not yet parses) CSS:

https://gist.github.com/DannyBen/59af3c3542068eeb125d62426cd1a090

**Comment by gingermusketeer** [comment]
```ruby
css['.main'] = {
    stroke: "green"
  }

  text "without attributes"
```
Is inconsistent with how other nodes are created. Is there an acceptable alternative to this inconsistency? For example helper functions for css and inline blocks for text? This might look like:

```ruby
style Victor.css('.main', stroke: "green")
text { _ "without attributes" } 
# or perhaps text {"without attributes"} but this is also inconsistent
```

Re the array vs hash for the intermediate representation of the SVG file it was to allow destructuring. I think a PORO would be better than a hash so that we have somewhere to add methods to make the code more readable.

**Comment by DannyBen** [comment]
Leave the CSS bit for now. I need to think about it and have some ideas.

If you can make it so the parser (in whichever version) and code generator can take care of the `text "hello", x: 10` form properly, and just dump the CSV string as is, we can merge so at least it works, and take care of the CSS later.

For now, the CSS can be easily integrated as a string using:

```ruby
svg.css = clean_csv_string   # without CDATA wrapper
```

**Comment by gingermusketeer** [comment]
@DannyBen Implemented the desired changes however the tests are now failing as the fixtures gem does not appear to support ruby objects. As it is a gem of yours do you have a suggestion for how to resolve this?

**Comment by DannyBen** [comment]
I will take a look.

**Comment by DannyBen** [comment]
Well, this became a little messy, but at least it works now, if we ignore the CSS that is not really converting that well.

This is what I did:

1. Change the `inspect` in the parser test, to `to_yaml` - so the fixtures are easy to read and verify.
2. Renamed `XmlNode` and `XmlText` to `XMLNode` and `XMLText`
3. Compacted `XMLText` - I don't see a reason to keep both `text` and `cleaned_text` - so its now just `text`, which is clean
4. I always put `attr_reader` at the top, and public. Since it almost always represents data that was given to the object form the outside on initialization, I see no reason to hide it.

I am not crazy about how it works now, it seems to fragile, but I guess we can merge and refactor later.

**Comment by DannyBen** [comment]
> how would you convert XMLHTTPRequest to snake case, without needing to specify rules to handle it? I realise this is not a very popular opinion.

Yes, but [this is the ruby way](https://github.com/rubocop-hq/ruby-style-guide#camelcase-classes):

> Use CamelCase for classes and modules. (Keep acronyms like HTTP, RFC, XML uppercase).

In any case - I will merge and release a version.
Will think about refactor + CSS handling later.

**Pull request merged**
